compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

nmMode: hardlinks-local
pnpMode: loose

packageExtensions:
  "medusa-react@*":
    peerDependencies:
      "@medusajs/medusa": "*"
      "awilix": "*"
      "@tanstack/react-query": "*"

  "@medusajs/types@*":
    peerDependencies:
      "awilix": "*"
